development:
  adapter: postgresql
  encoding: unicode
  database: hacquity_development
  pool: 5
  username: hacquity
  password: forgreatjustice

test:
  adapter: postgresql
  encoding: unicode
  database: hacquity_test
  pool: 5
  username: hacquity
  password: forgreatjustice


